name: build our image

on:
  push:
    branches: main

env:
  PRODUCT_VERSION: '1.1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u cpwood --password-stdin
      - name: build the image
        run: |
          docker buildx build \
            --push \
            --file Dockerfile \
            --tag cpwood/watchproxy:latest \
            --tag cpwood/watchproxy:${{ env.PRODUCT_VERSION }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .